### ISSUE TITLE
Problem using the plugin in Android Studio 3.3

### ISSUE THREAD

**Issue by Loma95** [TilStehle/Java-Kotlin-Swift-Trace-Link-Recovery#2]
When i try to navigate to the analyze option i get an exception: 

update failed for AnAction(actions.EditorQueryAction) with ID=traceabilityrecovery.editorQueryAction: org/jetbrains/kotlin/psi/KtClass
java.lang.NoClassDefFoundError: org/jetbrains/kotlin/psi/KtClass
	at actions.EditorQueryAction.update(EditorQueryAction.java:62)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:136)
	at com.intellij.openapi.actionSystem.impl.Utils.doUpdate(Utils.java:257)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:202)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:153)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:227)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:363)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.fillMenu(ActionMenu.java:331)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.access$600(ActionMenu.java:55)
	at com.intellij.openapi.actionSystem.impl.ActionMenu$MenuListenerImpl.menuSelected(ActionMenu.java:285)
	at javax.swing.JMenu.fireMenuSelected(JMenu.java:1038)
	at javax.swing.JMenu$MenuChangeListener.stateChanged(JMenu.java:1118)
	at javax.swing.DefaultButtonModel.fireStateChanged(DefaultButtonModel.java:349)
	at javax.swing.DefaultButtonModel.setSelected(DefaultButtonModel.java:232)
	at javax.swing.JMenu.setSelected(JMenu.java:305)
	at javax.swing.JMenu.menuSelectionChanged(JMenu.java:1187)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.menuSelectionChanged(ActionMenu.java:249)
	at javax.swing.MenuSelectionManager.setSelectedPath(MenuSelectionManager.java:125)
	at javax.swing.plaf.basic.BasicMenuUI$Handler.mouseEntered(BasicMenuUI.java:511)
	at java.awt.Component.processMouseEvent(Component.java:6550)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.retargetMouseEnterExit(Container.java:4677)
	at java.awt.LightweightDispatcher.trackMouseEnterExit(Container.java:4655)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4506)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:646)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at com.intellij.openapi.actionSystem.impl.ActionMenu$UsabilityHelper.lambda$new$0(ActionMenu.java:379)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:246)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:417)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:344)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:384)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by TilStehle** [comment]
Hi Marvin,
sorry for the inconvenience!
The plugin depends on the kotlin plugin, which was not explicitly stated in the plugin.xml.
Please 
-pull the latest changes

-Add a Dependency to the kotlin plugin to your IntelliJ IDEA-SDK via File -> Project Structure -> SDKs -> your plugin SDK -> classpath -> + -> select the kotlin-plugin.jar from the Home Directory of your plugin SDK.
It should look something like C:\Program Files\JetBrains\IntelliJ IDEA Community Edition VersionNumber\plugins\Kotlin\lib\kotlin-plugin.jar
(see https://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_dependencies.html)

-check, whether the kotlin plugin is installed in the Version of IDEA in which you run the plugin

-please also note, that we changed the location of the *find linked elements* action to
*Go To ->"Corresponding element in second implementation"*. The shortcut is still 
crtl+ alt + u  (on Mac it should be Cmd+alt+U)
The index now is also refreshed automatically, when you change a file within the IDEA project. To update it with regard to the linked swift files, press crtl+alt + i

let me know, if there are any further problems.
Cheers,
Til

**Comment by Loma95** [comment]
Thank you for your help :)
You are right! When i add the kotlin-plugin.jar to the plugin SDK i can compile the plugin and run it in debug mode. But i still get the same error when i right click on a kotlin class to jump to the corresponding swift implementation. I think the error appears in the update method of the EditorQueryAction class where the plugin doesnt recognise that its a KtClass that i clicked on. When i click on java classes i dont have any problems. 

My question: Is it a use-case for your plugin to find the corresponding swift implementation for kotlin?

Greetings 

Marvin

**Comment by TilStehle** [comment]
Hi Marvin,
yes, it is a use case. For big Kotlin projects, however, the initial indexing process might be rather slow, as we use a rather immature kotlin parser to fill the index.

I just checked with my current IDEA version and the plugin is working for kotlin classes. I am downloading a fresh version of Android Studio right now and will check, what else might be missing on the class path.
Kind Regards,
Til

**Comment by TilStehle** [comment]
Hi Marvin,
the plugin is working fine, even on a fresh version of Android Studio on my machine... :/
The error message definately looks like there is still some library missing on the classpath in your setting.

I have tried building the plugin and installing it directly in a fresh installation of Android Studio and it worked om a kotlin class. I will attach a built version of the plugin to this comment (zip-File).
Maybe you want to try running Android Studio directly and installing the plugin from your hard disc and see if it runs.

If it does not, i will try to run the plugin on a different machine to figure out, what might be missing.

Sorry,
Til

[TraceabilityRecoveryPlugin.zip](https://github.com/TilStehle/Java-Kotlin-Swift-Trace-Link-Recovery/files/2808681/TraceabilityRecoveryPlugin.zip)

**Comment by Loma95** [comment]
It works now!  👍 

...using your attached version of the plugin.
It would be great if you add this version to a release section of the repository
that everyone can install it.

Thank you for your effort :)

Marvin

**Comment by TilStehle** [comment]
Great :+1: 
Thanks for the suggestion. I made a release with the prebuilt zip.
